group: edge
dist: trusty

language: java
jdk: oraclejdk8

install: true
before_install:
  - sudo apt update

  # docker-compose
  - sudo apt install -y python-pip curl jq
  - sudo pip install docker-compose httpie
  - sudo usermod -aG docker $(whoami)

  # kill whatever punning on pg port
  - true | sudo kill $(sudo lsof -t -i:5432)

script:
  - export root=$PWD

  # getting-started-jvm-vertx
  - cd $root/getting-started-jvm-vertx
  - bash gradlew clean build

  # reactive-microservices-jvm-vertx
  - cd $root/reactive-microservices-jvm-vertx
  - bash gradlew clean build

after_script:
  - bash gradlew --stop

cache:
  directories:
    - $HOME/.m2/
    - $HOME/.gradle
